export const arrDirectivos = [
    {
      id: 1,
      nombre: "Cruz Yupanqui Gladys Marcionila",
      cargo: "Rectora UNTELS",
      dependencia: "Rectorado",
      telefono: "(01) 7158878",
      anexo: 107,
      correo: {
        general: "rectorado@untels.edu.pe",
        personal: "gcruz@untels.edu.pe",
      },
    },
    {
      id: 2,
      nombre: "Vilca Cáceres Marina",
      cargo: "Vicerrectora Académico",
      dependencia: "Vicerrectorado Académico",
      telefono: "(01) 7158878",
      anexo: 111,
      correo: {
        general: "v.academico@untels.edu.pe",
        personal: "mvilca@untels.edu.pe",
      },
    },
    {
      id: 3,
      nombre: "Navarro Raymundo Ángel Fernando",
      cargo: "Vicerrector de Investigación",
      dependencia: "Vicerrectorado Investigación",
      telefono: "(01) 7158878",
      anexo: 109,
      correo: {
        general: "viceinvest@untels.edu.pe",
        personal: "anavarro@untels.edu.pe",
      },
    },
    {
      id: 4,
      nombre: "Valero Cajahuanca Julio Elvis",
      cargo: "Decano de la Facultad de Ingeniería y Gestión",
      dependencia: "Decanato",
      telefono: "(01) 7158878",
      anexo: 186,
      correo: { general: "jvalero@untels.edu.pe", personal: null },
    },
    {
      id: 5,
      nombre: "Ludeña Aucapure Gabriela Estefanía",
      cargo: "Jefa Órgano de Control Institucional - Jefatura",
      dependencia: "Jefatura",
      telefono: "(01) 7158878",
      anexo: 105,
      correo: { general: "oci@untels.edu.pe", personal: "gludena@untels.edu.pe" },
    },
    {
      id: 6,
      nombre: "Velarde Falconi Gierek Juan de Dios",
      cargo: "Secretario técnico de Procedimiento Administrativo Disciplinario.",
      dependencia: "Secretario técnico de Procedimiento Administrativo Disciplinario.",
      telefono: "(01) 7158878",
      anexo: 169,
      correo: {
        general: "secretaria.tecnica@untels.edu.pe",
        personal: "gvelardef@untels.edu.pe",
      },
    },
    {
      id: 7,
      nombre: "Alarcón Armas Luis Felipe",
      cargo: "Jefe Oficina de Planificación y Presupuesto",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 122,
      correo: {
        general: "opp@untels.edu.pe",
        personal: "lalarcon@untels.edu.pe",
      },
    },
    {
      id: 8,
      nombre: "Oncebay Santa Maria Kenyi Jhonathan",
      cargo: "Jefe Oficina de Asesoría Jurídica",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 136,
      correo: { general: "asesoria_legal@untels.edu.pe", personal: null },
    },
    {
      id: 9,
      nombre: "Collantes Hidalgo José Arnaldo",
      cargo: "Jefe Oficina de Gestión de la Calidad",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 184,
      correo: { general: "occa@untels.edu.pe", personal: null },
    },
    {
      id: 10,
      nombre: "Perea Pasquel Manuel Lizardo",
      cargo: "Jefe(e) Oficina de Cooperación y Relaciones Interinstitucionales",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 121,
      correo: { general: "cooperacion_int@untels.edu.pe", personal: null },
    },
    {
      id: 11,
      nombre: "Uribe Allauca Marly Karina",
      cargo: "Secretaria General",
      dependencia: "Secretaría General",
      telefono: "(01) 7158878",
      anexo: 103,
      correo: {
        general: "secretariageneral@untels.edu.pe",
        personal: "muribe@untels.edu.pe",
      },
    },
    {
      id: 12,
      nombre: "Vigo Sánchez Edwin Augusto",
      cargo: "Defensor Universitario",
      dependencia: "Defensoría Universitaria",
      telefono: "(01) 7158878",
      anexo: 160,
      correo: {
        general: "ofidefensoria@untels.edu.pe",
        personal: "evigo@untels.edu.pe",
      },
    },
    {
      id: 13,
      nombre: "Morales Paredes Waldo",
      cargo: "Director Dirección General de Administración",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 134,
      correo: {
        general: "dga@untels.edu.pe",
        personal: "wmorales@untels.edu.pe",
      },
    },
    {
      id: 14,
      nombre: "Almonacid Acevedo Hugo Yuver",
      cargo: "Jefe Unidad de Tesorería",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 147,
      correo: {
        general: "unidad_tesoreria@untels.edu.pe",
        personal: "halmonacid@untels.edu.pe",
      },
    },
    {
      id: 15,
      nombre: "Luyo Bazán Manuel Armando",
      cargo: "Jefe Unidad de Contabilidad",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 166,
      correo: {
        general: "contabilidad@untels.edu.pe",
        personal: "mluyo@untels.edu.pe",
      },
    },
    {
      id: 16,
      nombre: "Espinoza Calderón Anthony Iván",
      cargo: "Jefe Unidad de Abastecimiento",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 138,
      correo: {
        general: "abastecimiento@untels.edu.pe",
        personal: "aespinozac@untels.edu.pe",
      },
    },
    {
      id: 17,
      nombre: "Altamirano Márquez Edgar Leónidas",
      cargo: "Jefe Unidad de Recursos Humanos",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 104,
      correo: { general: "rrhh@untels.edu.pe", personal: null },
    },
    {
      id: 18,
      nombre: "Salazar Carhuarupay José Luis",
      cargo: "Jefe Unidad de Servicios Generales",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 150,
      correo: {
        general: "usg@untels.edu.pe",
        personal: "jsalazarc@untels.edu.pe",
      },
    },
    {
      id: 19,
      nombre: "Rivera Casamayor Juan Gabriel",
      cargo: "Jefe Unidad Ejecutora de Inversiones",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 191,
      correo: { general: "uei@untels.edu.pe", personal: "uei@untels.edu.pe" },
    },
    {
      id: 20,
      nombre: "Camero Ramírez Oscar James",
      cargo: "Jefe Oficina de Comunicación e Imagen Institucional",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 149,
      correo: { general: "imagen@untels.edu.pe", personal: null },
    },
    {
      id: 21,
      nombre: "Balseca Sánchez Filomena",
      cargo: "Directora Dirección de Bienestar Universitario",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 112,
      correo: {
        general: "obu@untels.edu.pe",
        personal: "fbalseca@untels.edu.pe",
      },
    },
    {
      id: 22,
      nombre: "Marcelino Tarmeño Edgar Avelino",
      cargo: "Director Dirección de Responsabilidad Social y Universitaria.",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 153,
      correo: { general: "direccion.rsu@untels.edu.pe", personal: null },
    },
    {
      id: 23,
      nombre: "Daga Chaca Esther Evelyn",
      cargo: "Jefe Oficina de Tecnologías de la Información y Comunicación",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 170,
      correo: { general: "otic@untels.edu.pe", personal: "edaga@untels.edu.pe" },
    },
    {
      id: 24,
      nombre: "Ochoa Gamarra Mirtha",
      cargo: "Directora Dirección de Registros Académicos",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 146,
      correo: {
        general: "registro.matricula@untels.edu.pe",
        personal: "mochoa@untels.edu.pe",
      },
    },
    {
      id: 25,
      nombre: "Trujillo Hinojosa Cesar",
      cargo: "Jefe Oficina de Gestión Académica y Prospectiva",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 120,
      correo: { general: "ogap@untels.edu.pe", personal: null },
    },
    {
      id: 26,
      nombre: "Torres Isla Julio Cesar",
      cargo: "Director Dirección de Admisión",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 116,
      correo: { general: "admision@untels.edu.pe", personal: null },
    },
    {
      id: 27,
      nombre: "San Bartolome Montero Jaime Hewer",
      cargo: "Jefe CEPREUNTELS",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 183,
      correo: { general: "cepreuntels@untels.edu.pe", personal: null },
    },
    {
      id: 29,
      nombre: "Castro León Gloria Helena",
      cargo: "Jefe Comité Electoral Universitario",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 189,
      correo: { general: "comite_electoral@untels.edu.pe", personal: null },
    },
    {
      id: 30,
      nombre: "Ruiz Huamán Carmen Milagros",
      cargo: "Jefe Comité Seguridad y Salud",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 188,
      correo: { general: "comite_sst@untels.edu.pe", personal: null },
    },
    {
      id: 31,
      nombre: "Vilca Ccolque Jose Yudberto",
      cargo: "Director Escuela Profesional de Administración de Empresas",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 129,
      correo: { general: "admempresas@untels.edu.pe", personal: null },
    },
    {
      id: 32,
      nombre: "Ruiz Huaman Carmen Milagros",
      cargo: "Director Escuela Profesional de Ingeniería Ambiental",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 126,
      correo: { general: "ingambiental@untels.edu.pe", personal: null },
    },
    {
      id: 33,
      nombre: "Larios Franco Alfredo Cesar",
      cargo: "Director Escuela Profesional de Ingeniería de Sistemas",
      dependencia: "",
      telefono: "(01) 7158878",
      anexo: 128,
      correo: { general: "escuelaingsistemas@untels.edu.pe", personal: null },
    },
    {
        id: 34,
        nombre: "Lezama Calvo Jinmi Gregory",
        cargo: "Director Escuela Profesional de Ingeniería Electrónica y Telecomunicaciones",
        dependencia: "",
        telefono: "(01) 7158878",
        anexo: 127,
        correo: { general: "iet@untels.edu.pe", personal: null },
      },
      {
        id: 35,
        nombre: "Pfuyo Muñoz Roberto",
        cargo: "Director Escuela Profesional de Ingeniería Mecánica y Eléctrica",
        dependencia: "",
        telefono: "(01) 7158878",
        anexo: 143,
        correo: { general: "ime@untels.edu.pe", personal: null },
      },
      {
        id: 36,
        nombre: "Román González Avid",
        cargo: "Director",
        dependencia: "Instituto de Investigación",
        telefono: "(01) 7158878",
        anexo: 125,
        correo: {
          general: "instituto_investigacion@untels.edu.pe",
          personal: null,
        },
      },
      {
        id: 37,
        nombre: "Clemente Arenas Mark Donny",
        cargo: "Coordinador",
        dependencia: "Escuela de Posgrado",
        telefono: "(01) 7158878",
        anexo: 169,
        correo: { general: "escuela_posgrado@untels.edu.pe", personal: null },
      },
      {
        id: 38,
        nombre: "Luque Rivera Jesus Virgilio",
        cargo: "Coordinador",
        dependencia: "Programa de Estudios Generales",
        telefono: "(01) 7158878",
        anexo: 114,
        correo: { general: "estudiosgenerales@untels.edu.pe", personal: null },
      },
];

arrDirectivos.map(obj => {
    const {anexo, correo, cargo} = obj;
    console.log(anexo, correo, cargo);
})